### ISSUE TITLE
使用后仍然锁区

### ISSUE THREAD

**Issue by SteveXiao0510** [yi-ji/NeteaseMusicAbroad#18] opened 2018-11-05 01:16 UTC
之前一段时间可以用的，前几天开始就没法破解了，很感谢大神的软件，希望能帮忙看看🙏

2018-11-04 20:11:14-0500 [-] Log opened.
2018-11-04 20:11:15-0500 [-] Traceback (most recent call last):
2018-11-04 20:11:15-0500 [-]   File "/Users/shaw/anaconda3/lib/python3.7/site-packages/twisted/internet/tcp.py", line 1361, in startListening
2018-11-04 20:11:15-0500 [-]     skt.bind(addr)
2018-11-04 20:11:15-0500 [-] OSError: [Errno 48] Address already in use
2018-11-04 20:11:15-0500 [-] 
2018-11-04 20:11:15-0500 [-] During handling of the above exception, another exception occurred:
2018-11-04 20:11:15-0500 [-] 
2018-11-04 20:11:15-0500 [-] Traceback (most recent call last):
2018-11-04 20:11:15-0500 [-]   File "NeteaseMusicProxy.py", line 255, in <module>
2018-11-04 20:11:15-0500 [-]     reactor.listenTCP(32794, NeteaseMusicProxyFactory())
2018-11-04 20:11:15-0500 [-]   File "/Users/shaw/anaconda3/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2018-11-04 20:11:15-0500 [-]     p.startListening()
2018-11-04 20:11:15-0500 [-]   File "/Users/shaw/anaconda3/lib/python3.7/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2018-11-04 20:11:15-0500 [-]     raise CannotListenError(self.interface, self.port, le)
2018-11-04 20:11:15-0500 [-] twisted.internet.error.CannotListenError: Couldn't listen on any:32794: [Errno 48] Address already in use.

**Comment by SteveXiao0510** [comment] 2018-11-05 01:18
Shaws-MacBook-Pro:NeteaseMusicAbroad-master shaw$ python -V
Python 3.7.0
Shaws-MacBook-Pro:NeteaseMusicAbroad-master shaw$ pip -V
pip 10.0.1 from /Users/shaw/anaconda3/lib/python3.7/site-packages/pip (python 3.7)

**Comment by yi-ji** [comment] 2018-11-05 01:42
端口被占用，应该是因为之前的进程没有退掉，只需要退出网易云音乐或者`kill -9 `ps x | grep NeteaseMusic | awk '{print $1}'``

极小可能是有别的进程占了32794端口，如果上述仍无效请查看`lsof -nP -iTCP:$PORT | grep LISTEN`

**Comment by INPUTrrr0** [comment] 2018-11-05 21:14
我也有同样的问题orz
输出是：
2018-11-05 16:12:09-0500 [-] Log opened.
2018-11-05 16:12:10-0500 [-] NeteaseMusicProxyFactory starting on 32794
2018-11-05 16:12:10-0500 [-] Starting factory <__main__.NeteaseMusicProxyFactory instance at 0x10c824dd0>
谢谢！

**Comment by INPUTrrr0** [comment] 2018-11-05 21:17
kill之后再打开网易云音乐执行“lsof -nP -iTCP:32794 | grep LISTEN”之后是：Python  20922 theone    8u  IPv4 0xae15f6ab40277d5d      0t0  TCP *:32794 (LISTEN)

**Comment by yi-ji** [comment] 2018-11-06 00:33
@INPUTrrr0 可能跟 #16 问题相同，请重新下载最新的NeteaseMusicAbroad使用

**Comment by yi-ji** [comment] 2018-11-07 02:48
Duplicate of #8

**Closed by yi-ji** 2018-11-07 02:48 UTC
Labels: help wanted

**Comment by INPUTrrr0** [comment] 2018-11-08 02:04
> @INPUTrrr0 可能跟 #16 问题相同，请重新下载最新的NeteaseMusicAbroad使用

好的！现在可以用啦！非常感谢！超级棒！！辛苦啦
